### PR TITLE
Improve layouts and image resources to better match Material Design guidelines.

### PR DESCRIPTION
**Pull request by JediBurrell**
This PR replaces old Android resources with Material resources, updates the icon to match Material Design guidelines, as well as using the new Android O Adaptive Icons, and a few small layout changes.

### CODE REVIEW

**Comment by ScreamingHawk** [comment]
Wow that's so much nicer. I don't have any formal training in android so everything I've done has been self taught guess work. 

Do you know of any sources/vids/tutorials etc that would be a good starting point for me to understand the things you've fixed? 

Thanks a lot for the this!

**Comment by JediBurrell** [comment]
I'm also self taught, though I've been working on apps since 2.3.4 Gingerbread. I mainly learned design from an interest in Material Design when Android Lollipop came out. [Here's the official website/guidelines by Google](https://material.io/).

I can try to explain what I did, however.

For some reason Android doesn't update their drawable resources ( You were using @android:drawable/ic_input_add as well as some other resources, which came out in Android 2.1 - from 2009 ), so I downloaded the various icons from here: https://material.io/icons/ ( by Google ) - changed all the references to the new icons.

All of the ImageButton's were changed with the new icons, and the backgrounds were replaced with `?selectableItemBackgroundBorderless`, a transparent background with a borderless ( circle ) ripple. Replacing the background removed the additional space the button gave, so I also added some padding.

In `@layout/character_edit_description` there were buttons with "+" and "-" for the points, I replaced these with ImageButtons as were described.

You were using headers, though the root view's all had padding, which made it a floating section. I slightly increased the padding on the headers (`@dimen/section_title_padding`) from 2dp to 16dp to give the text a little bit of extra room. Removed the root view's paddings, and wrapped everything else ( excluding the headers ) in a child view with the same padding. I also seperated the headers with a 1dp view of 12% black ( On a dark theme, it would be white. )

And then lastly, following the guidelines, I replaced the app icons with a Material Design version of it. And exported a 432x432 (108dp) version of a clipless background and foreground alongside the main icon resources, and created the adaptive-icon in `drawable-anydpi`.

**Comment by ScreamingHawk** [comment]
This change has stopped the app icon appearing and also broken the credits page. If you've got a quick fix for this it will be greatly appreciated. If not, thanks for the changes so far I'll pick it up when I get back to dev on this. 

Edit: Just read through your comment. Thanks for detailing all that. Makes a lot of sense.

**Comment by JediBurrell** [comment]
Yeah, extremely simple fix, I'll take care of it once I get home.

**Pull request merged**
